server:
  port: 8000
spring:
  application:
    name: cambio-service
  datasource:
    url: jdbc:mysql://localhost:3306/cambio-service?useTimezone=true&serverTimezone=UTC
    username: root
    password: 1804
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false

springdoc:
  api-docs:
    path: cambio-service/v3/api-docs
  swagger-ui:
    config-url: /cambio-service/v3/api-docs/swagger-config
    url: /cambio-service/v3/api-docs

management:
  tracing:
    sampling:
      probability: 1.0