version: '3.4'
services:
  zipkin-server:
    image: openzipkin/zipkin:2.23.2
    ports:
      - 9411:9411
    depends_on:
      - rabbit-mq
    restart: always
    environment:
      RABBIT_URI: amqp://guest:guest@rabbit-mq:5672
    networks:
      - caioprog-network

  rabbit-mq:
    image: rabbitmq:3.8.14-management
    ports:
      - 5672:5672
      - 15672:15672
    networks:
      - caioprog-network

  cambio-db:
    image: mysql:8.3.0
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - 3308:3308
    depends_on:
      - naming-server
    environment:
      TZ: America/Sao_Paulo
      MYSQL_ROOT_PASSWORD: 1804
      MYSQL_USER: docker
      MYSQL_PASSWORD: 1804
      MYSQL_DATABASE: cambio-service
      MYSQL_ROOT_HOST: '%'
      MYSQL_TCP_PORT: 3308
    expose:
      - 3308
    networks:
      - caioprog-network

  book-db:
    image: mysql:8.3.0
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - 3310:3310
    depends_on:
      - naming-server
    environment:
      TZ: America/Sao_Paulo
      MYSQL_ROOT_PASSWORD: 1804
      MYSQL_USER: docker
      MYSQL_PASSWORD: 1804
      MYSQL_DATABASE: book-service
      MYSQL_ROOT_HOST: '%'
      MYSQL_TCP_PORT: 3310
    expose:
      - 3310
    networks:
      - caioprog-network

  naming-server:
    image: caioprog/naming-server:0.0.1-SNAPSHOT
    ports:
      - 8761:8761
    networks:
      - caioprog-network

  api-gateway:
    image: caioprog/api-gateway:0.0.1-SNAPSHOT
    ports:
      - 8765:8765
    depends_on:
      - naming-server
      - rabbit-mq
    environment:
      SPRING.APLICATION.NAME: api-gateway
      SPRING_APPLICATION_JSON: '{"eureka":{"client":{"serviceUrl":{"defaultZone":"http://naming-server:8761/eureka"}}}}'
      EUREKA.CLIENT.SERVICEURL.DEFAULTZONE: http://naming-server:8761/eureka
      SPRING.ZIPKIN.BASEURL: http://zipkin-server:9411/
      RABBIT_URI: amqp://guest:guest@rabbit-mq:5672
      SPRING_RABBITMQ_HOST: rabbit-mq
      SPRING_ZIPKIN_SENDER_TYPE: rabbit
    networks:
      - caioprog-network

  cambio-service:
    image: caioprog/cambio-service
    restart: always
    build:
      context: .
      dockerfile: cambio-service/Dockerfile
    environment:
      TZ: America/Sao_Paulo
      SPRING.APLICATION.NAME: cambio-service
      SPRING_APPLICATION_JSON: '{"eureka":{"client":{"serviceUrl":{"defaultZone":"http://naming-server:8761/eureka"}}}}'
      EUREKA.CLIENT.SERVICEURL.DEFAULTZONE: http://naming-server:8761/eureka
      SPRING.ZIPKIN.BASEURL: http://zipkin-server:9411/
      SPRING.DATASOURCE.URL: jdbc:mysql://cambio-db:3308/cambio-service?useSSL=false&serverTimezone=UTC&enabledTLSProtocols=TLSv1.2
      SPRING.DATASOURCE.USERNAME: root
      SPRING.DATASOURCE.PASSWORD: 1804
      SPRING.FLYWAY.URL: jdbc:mysql://cambio-db:3308/cambio-service?useSSL=false&serverTimezone=UTC&enabledTLSProtocols=TLSv1.2
      SPRING.FLYWAY.USER: root
      SPRING.FLYWAY.PASSWORD: 1804
      RABBIT_URI: amqp://guest:guest@rabbit-mq:5672
      SPRING_RABBITMQ_HOST: rabbit-mq
      SPRING_ZIPKIN_SENDER_TYPE: rabbit
    ports:
      - 8000:8000
    depends_on:
      - naming-server
      - cambio-db
      - rabbit-mq
    networks:
      - caioprog-network

  book-service:
    image: caioprog/book-service
    restart: always
    build:
      context: .
      dockerfile: book-service/Dockerfile
    environment:
      TZ: America/Sao_Paulo
      SPRING.APLICATION.NAME: book-service
      SPRING_APPLICATION_JSON: '{"eureka":{"client":{"serviceUrl":{"defaultZone":"http://naming-server:8761/eureka"}}}}'
      EUREKA.CLIENT.SERVICEURL.DEFAULTZONE: http://naming-server:8761/eureka
      SPRING.ZIPKIN.BASEURL: http://zipkin-server:9411/
      SPRING.DATASOURCE.URL: jdbc:mysql://book-db:3310/book-service?useSSL=false&serverTimezone=UTC&enabledTLSProtocols=TLSv1.2
      SPRING.DATASOURCE.USERNAME: root
      SPRING.DATASOURCE.PASSWORD: 1804
      SPRING.FLYWAY.URL: jdbc:mysql://book-db:3310/book-service?useSSL=false&serverTimezone=UTC&enabledTLSProtocols=TLSv1.2
      SPRING.FLYWAY.USER: root
      SPRING.FLYWAY.PASSWORD: 1804
      RABBIT_URI: amqp://guest:guest@rabbit-mq:5672
      SPRING_RABBITMQ_HOST: rabbit-mq
      SPRING_ZIPKIN_SENDER_TYPE: rabbit
    ports:
      - 8100:8100
    depends_on:
      - naming-server
      - cambio-service
      - book-db
      - rabbit-mq
    networks:
      - caioprog-network

networks:
  caioprog-network:
    driver: bridge
