server:
  port: 8100
spring:
  application:
    name: book-service
  datasource:
    url: jdbc:mysql://localhost:3306/book-service?useTimezone=true&serverTimezone=UTC
    username: root
    password: 1804
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false

resilience4j:
  bulkhead:
    instances:
      default:
        max-concurrent-calls: 10
  ratelimiter:
    instances:
      default:
        limit-for-period: 2
        limit-refresh-period: 10s
  retry:
    instances:
      default:
        max-attempts: 5
        wait-duration: 1s
        enable-exponential-backoff: true
springdoc:
  api-docs:
    path: book-service/v3/api-docs
  swagger-ui:
    config-url: /book-service/v3/api-docs/swagger-config
    url: /book-service/v3/api-docs

management:
  tracing:
    sampling:
      probability: 1.0